services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres  # Specifies the data directory
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped

  config-server-ms:
    image: arpitapatil372/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - "8080:8080"
    depends_on:
      - servicereg #depends on tells run first mentioned image 
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker 

  servicereg:
    image: arpitapatil372/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres

  companyms:
    image: arpitapatil372/companyms:latest
    container_name: company
    ports:
      - "8081:8081"
    depends_on:
      - servicereg 
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker  

  jobms:
    image: arpitapatil372/jobms:latest
    container_name: job
    ports:
      - "8082:8082"
    depends_on:
      - servicereg 
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka 
   
  reviewms:
    image: arpitapatil372/reviewms:latest
    container_name: review
    ports:
      - "8083:8083"
    depends_on:
      - servicereg 
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker  

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres

  gateway-ms:
    image: arpitapatil372/gateway-ms:latest
    ports:
      - "8084:8084"
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
